[tox]
envlist =
    lint
    typecheck
    py{310,311,312,313}
skip_missing_interpreters = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/p2pclient
extras = test
commands =
    pytest --cov=./p2pclient --daemon=p2pd tests/

[testenv:lint]
extras = lint
commands =
    ruff check p2pclient/ tests/
    ruff format --check p2pclient/ tests/

[testenv:typecheck]
extras =
    test
    lint
commands =
    mypy -p p2pclient
