[tox]
envlist =
    lint
    typecheck
    py{39,310,311,312,313}

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/p2pclient
extras = test
commands =
    pytest --cov=./p2pclient --daemon=p2pd tests/

[testenv:lint]
extras = lint
commands =
    ruff check p2pclient/ tests/
    ruff format --check p2pclient/ tests/

[testenv:typecheck]
extras = lint
commands =
    mypy -p p2pclient --config-file {toxinidir}/mypy.ini
